import './globals.css'
import localFont from 'next/font/local'

const avenixRegular = localFont({
  src: '../assets/Fontes/Avenix-Regular.otf',
  display: 'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={avenixRegular.className}>{children}</body>
    </html>
  )
}
